### ISSUE TITLE
Bad news : stable diffusion api from replicate has expired it needs a replacement

### ISSUE THREAD

**Issue by AymanLyesri** [AymanLyesri/project-ai-image-generation#12]
I was working with the api created by replicate, but i discovered its only paid, the free demo has expired :(

Any other api replacement?? i seached and there is only one other from [DreamStudio](https://beta.dreamstudio.ai/) that is temp free

here the documentation for its  [typescript api](https://github.com/jakiestfu/stability-ts)

i got it working as a mjs (js module) but when i enter the parameters for image end send it, the http response says "not enougth parameters"

any suggestions??

**Comment by Gri-ffin** [comment]
we can use [stability-client](https://github.com/vpzomtrrfrt/stability-client)
